-- Indra Hotel Initial Seed Data with Multi-Language (i18n) Support
-- Supported Locales: en (English), km (Khmer), zh (Chinese), ko (Korean)

INSERT INTO `users` (`id`, `name`, `email`, `password_hash`, `role`, `avatar`) VALUES
(1, 'Hotel Manager', 'admin@hotel.com', '$2y$10$wzVdK3p240.g84Y1o1e9..B.e6TqH9Q8u0k92K4Z00hK4WlQWjJ1e', 'admin', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80'),
(2, 'Front Desk Editor', 'editor@hotel.com', '$2y$10$iGgI9k0yDfvN9GkY.f/1E.3Y1aYjW2bCkn4fM8Lp7eG8R7B3x1V9q', 'editor', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80')
ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `role`=VALUES(`role`);

-- Insert Rooms & Suites with Full Multi-Language Translations JSON
INSERT INTO `rooms` (`id`, `name`, `slug`, `tagline`, `description`, `price_per_night`, `size_sqm`, `bed_type`, `capacity_adults`, `capacity_children`, `view_type`, `image_url`, `gallery_json`, `amenities_json`, `translations_json`, `status`, `is_featured`, `display_order`) VALUES
(1, 'Deluxe King Room', 'deluxe-king', 'Contemporary Sanctuary for Modern Travelers', 'With modern and functional decor, our Deluxe King Room offers a serene and cozy environment perfect for unwinding and relaxation. Features a plush king-sized bed, high-speed WiFi, flat-screen smart TV, private minibar, artisan coffee station, and a luxurious en-suite bathroom stocked with organic bath amenities.', 85.00, 38, '1 King Bed', 2, 1, 'City View', 'https://lh3.googleusercontent.com/aida/AP1WRLs-aT78HuC87zVBtlw78IAcVeqttvz1DzuDCFkgHQa0GjAqpJ7QEgkbAcIsJqkihNQyvb5xyVUyfpGCLZpUTsGnoI_Zd2-vfG3hGgzgX8ILxOjMzXh6zptxCM2mUT_5SpyirJMD2KE7cfOEm3QbJ69fnH6VMjX0sVrsXmM5Jm-XtIvZg9-B3Mseq2ffcjkq7LNDstvkdy5lRLn-NIFXZWhKbwJ1tFsvSH-_tFiOrkWNTCNfDxbD8XbxG-j2', '["https://lh3.googleusercontent.com/aida/AP1WRLs-aT78HuC87zVBtlw78IAcVeqttvz1DzuDCFkgHQa0GjAqpJ7QEgkbAcIsJqkihNQyvb5xyVUyfpGCLZpUTsGnoI_Zd2-vfG3hGgzgX8ILxOjMzXh6zptxCM2mUT_5SpyirJMD2KE7cfOEm3QbJ69fnH6VMjX0sVrsXmM5Jm-XtIvZg9-B3Mseq2ffcjkq7LNDstvkdy5lRLn-NIFXZWhKbwJ1tFsvSH-_tFiOrkWNTCNfDxbD8XbxG-j2","https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80"]', '["High-Speed Wi-Fi","55\" Smart Cable TV","Artisan Coffee Maker","Minibar & Refrigerator","In-Room Electronic Safe","Air Conditioning","Organic Bath Amenities","Rainfall Shower","Work Desk & Ergonomic Chair","Daily Housekeeping"]', '{"en":{"name":"Deluxe King Room","tagline":"Contemporary Sanctuary for Modern Travelers","description":"With modern and functional decor, our Deluxe King Room offers a serene and cozy environment perfect for unwinding and relaxation. Features a plush king-sized bed, high-speed WiFi, flat-screen smart TV, private minibar, artisan coffee station, and a luxurious en-suite bathroom."},"km":{"name":"បន្ទប់ ឌីឡាក់ឃីង (Deluxe King)","tagline":"ទីជម្រកដ៏ស្ងប់ស្ងាត់សម្រាប់អ្នកដំណើរទាន់សម័យ","description":"ជាមួយនឹងការតុបតែងបែបទំនើប និងមានមុខងារ បន្ទប់ ឌីឡាក់ឃីង របស់យើងផ្តល់នូវបរិយាកាសស្ងប់ស្ងាត់ និងកក់ក្តៅ ស័ក្តិសមបំផុតសម្រាប់ការសម្រាកលំហែកាយ។ បំពាក់ដោយគ្រែឃីងដ៏មានផាសុកភាព អ៊ីនធឺណិតល្បឿនលឿន ទូរទស្សន៍ឆ្លាតវៃ មីនីបារ និងបន្ទប់ទឹកប្រណិត។"},"zh":{"name":"豪华大床房 (Deluxe King)","tagline":"专为现代商务与休闲旅客打造的当代庇护所","description":"豪华大床房拥有现代实用的装潢，营造出宁静舒适的居停环境，是放松身心的理想之选。配有豪华特大床、高速无线网络、智能液晶电视、私人迷你吧、手冲咖啡台以及配备有机洗浴用品的典雅卫浴。"},"ko":{"name":"디럭스 킹 룸 (Deluxe King)","tagline":"현대 여행자를 위한 도심 속 안식처","description":"모던하고 실용적인 인테리어를 갖춘 디럭스 킹 룸은 휴식과 재충전을 위한 평온하고 아늑한 분위기를 제공합니다. 고급 킹사이즈 침대, 초고속 와이파이, 스마트 TV, 미니바 및 오가닉 어메니티를 구비하고 있습니다."}}', 'available', 1, 1),

(2, 'Junior Suite with Balcony', 'junior-suite', 'Spacious Urban Retreat with Private Terrace', 'Enjoy the added luxury of a private terrace balcony overlooking the serene Tuol Kork neighborhood. The Junior Suite combines refined contemporary aesthetics with expansive living spaces, a dedicated lounge seating area, custom wooden furnishings, and premium bathrobes for optimal relaxation.', 125.00, 48, '1 King Bed + Daybed', 3, 1, 'Garden & City View', 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1200&q=80"]', '["Private Balcony with Seating","High-Speed Wi-Fi","65\" 4K Smart TV","Espresso Machine","Well-Stocked Minibar","Deep Soaking Tub & Rain Shower","Organic Toiletries","Plush Bathrobes & Slippers","Lounge Seating Area","Safety Deposit Box"]', '{"en":{"name":"Junior Suite with Balcony","tagline":"Spacious Urban Retreat with Private Terrace","description":"Enjoy the added luxury of a private terrace balcony overlooking the serene Tuol Kork neighborhood. The Junior Suite combines refined contemporary aesthetics with expansive living spaces, a dedicated lounge seating area, custom wooden furnishings, and premium bathrobes."},"km":{"name":"បន្ទប់ ជូនៀស៊្វីត មានយ៉រ (Junior Suite)","tagline":"បន្ទប់ធំទូលាយប្រណិត ជាមួយយ៉រផ្ទាល់ខ្លួន","description":"រីករាយជាមួយភាពប្រណិតបន្ថែមនៃយ៉រផ្ទាល់ខ្លួនដែលមើលឃើញទេសភាពដ៏ស្ងប់ស្ងាត់នៃខណ្ឌទួលគោក។ បន្ទប់ ជូនៀស៊្វីត រួមបញ្ចូលគ្នានូវសោភ័ណភាពបែបសហសម័យ ជាមួយនឹងកន្លែងរស់នៅធំទូលាយ បន្ទប់ទទួលភ្ញៀវ និងគ្រឿងសង្ហារឹមឈើប្រណិត។"},"zh":{"name":"阳台轻奢套房 (Junior Suite)","tagline":"拥有私人景观阳台的宽敞都市居所","description":"专享俯瞰堆谷区宁静街景的私人阳台露台。轻奢套房将精致现代美学与宽敞居住空间融为一体，配备独立会客休息区、定制实木家具与高档浴袍，为您带来惬意享受。"},"ko":{"name":"발코니 주니어 스위트 (Junior Suite)","tagline":"개인 테라스 발코니를 갖춘 여유로운 휴식 공간","description":"툴콕 지역의 평화로운 전망을 감상할 수 있는 프라이빗 발코니를 즐겨보세요. 주니어 스위트는 세련된 모던 감성과 넓은 거실 공간, 라운지 좌석, 원목 가구가 조화를 이룹니다."}}', 'available', 1, 2),

(3, 'Indra Suite with Balcony', 'indra-suite', 'The Pinnacle of Khmer Elegance & Luxury', 'Our signature residence exudes prestigious comfort and sustainable charm. Featuring an expansive master bedroom, separate open-plan living room, private sun terrace balcony with lush greenery, walk-in closet, and spa-inspired marble bathroom. Perfect for discerning travelers seeking an elite haven in Phnom Penh.', 180.00, 68, '1 Grand King Bed', 3, 2, 'Panoramic Skyline View', 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=1200&q=80"]', '["Expansive Private Panoramic Balcony","Separate Living Room","High-Speed Wi-Fi","Two 65\" Smart TVs","Signature Nespresso Station","Complimentary Premium Minibar","Marble Bathroom with Free-standing Tub","Walk-in Dressing Closet","In-Room Dining Service","VIP Airport Transfer Option"]', '{"en":{"name":"Indra Suite with Balcony","tagline":"The Pinnacle of Khmer Elegance & Luxury","description":"Our signature residence exudes prestigious comfort and sustainable charm. Featuring an expansive master bedroom, separate open-plan living room, private sun terrace balcony with lush greenery, walk-in closet, and spa-inspired marble bathroom."},"km":{"name":"បន្ទប់ ឥន្ទ្រាស៊្វីត មានយ៉រ (Indra Suite)","tagline":"កំពូលនៃភាពថ្លៃថ្នូរ និងប្រណិតភាពបែបខ្មែរ","description":"បន្ទប់ស្នាក់នៅដ៏ឆ្នើមរបស់យើងបង្ហាញពីផាសុកភាពដ៏ឧត្តុង្គឧត្តម។ មានបន្ទប់គេងមេធំទូលាយ បន្ទប់ទទួលភ្ញៀវដាច់ដោយឡែក យ៉រមើលទេសភាពបៃតង បន្ទប់ផ្លាស់សម្លៀកបំពាក់ និងបន្ទប់ទឹកថ្មម៉ាបបែបស្ប៉ា។"},"zh":{"name":"因陀罗尊贵全景套房 (Indra Suite)","tagline":"高棉典雅与奢华居停的至臻典范","description":"酒店旗舰级行政套房，尽显尊崇舒适与环保魅力。配备超大主卧、独立开放式起居室、郁郁葱葱的全景私人景观阳台、步入式衣帽间及大理石水疗浴室。"},"ko":{"name":"인드라 프레지덴셜 스위트 (Indra Suite)","tagline":"크메르의 우아함과 최상의 럭셔리가 깃든 시그니처 객실","description":"인드라 호텔의 시그니처 스위트로 최고의 품격과 편안함을 선사합니다. 넓은 마스터 침실, 독립된 거실, 프라이빗 테라스, 드레스룸 및 최고급 대리석 욕실을 갖추고 있습니다."}}', 'available', 1, 3)
ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `translations_json`=VALUES(`translations_json`);

-- Insert Dining & Wellness
INSERT INTO `dining_wellness` (`id`, `type`, `title`, `subtitle`, `description`, `hours`, `price_range`, `image_url`, `menu_items_json`, `is_published`, `display_order`) VALUES
(1, 'dining', 'The Indra Bistro & Cafe', 'Artisanal Coffee & Contemporary International Dining', 'Indulge in a range of culinary experiences featuring international and Asian-fusion cuisine with a contemporary twist. From a delectable breakfast at the cafe to fine dining and sunset cocktails, our sophisticated surroundings provide the perfect backdrop for an unforgettable dining experience.', '06:30 AM - 10:30 PM', '$$ - $$$', 'https://lh3.googleusercontent.com/aida/AP1WRLu4xqDm5eXV-bc_ApYrUK1GnN0Euq-6ES4WN642l6K8VhewdBb_YkEtWSSt-tybo0AKJFBQh2oRWlfCx42rbsSmJsLPSmn2ODfXDog-y3cHuE5NTuWtSDiZptOZNk-bMlpk3s-xS7TRQHWRaUeUH0_bRiicGwQeGjy6gBDbaO4KosbM7QsKUNWT0PhQSHXUnhupahrd4i6fqtDtt53ZX2XGRn06_VQba3YHrkQ1BSNwkc5KeAJ3nMpX63ho', '[{"name":"Traditional Khmer Fish Amok","price":"$14.00","desc":"Steamed sea bass fillet in rich aromatic coconut lemongrass curry served in banana leaf."},{"name":"Angus Ribeye Steak 250g","price":"$28.00","desc":"Char-grilled prime beef served with Kampot green peppercorn sauce and truffle mashed potatoes."},{"name":"Signature Indra Benedict","price":"$9.50","desc":"Poached farm eggs, smoked salmon, avocado, brioche bun, and homemade yuzu hollandaise."},{"name":"Kampot Pepper Crab Fried Rice","price":"$12.50","desc":"Fragrant Jasmine rice wok-tossed with fresh blue crab meat, garlic, and fresh Kampot pepper."}]', 1, 1),

(2, 'wellness', 'Fitness Center & Saltwater Pool', 'State-of-the-Art Training & Serene Swimming', 'Our guests can stay fit and healthy with our fully equipped fitness center, open from 7:00am till 9:00pm. Complete with state-of-the-art training gear, cardiovascular machines, free weights, and a refreshing outdoor saltwater pool nestled in a lush tropical garden setting.', '07:00 AM - 09:00 PM', 'Complimentary for Guests', 'https://lh3.googleusercontent.com/aida/AP1WRLuptPITXoiXpQR1wIOmYOuIMSUpJR1sTCXJga7uhGTXxKzccE6d21YAs-Fz3vugKf8Di3bkOx3Z2SAFqzNx65b_Uw7N7kpd85zK1LmfmQdCORWGDlOrtH72JS6rhGzsyzxnD8WonzUh6ObvlE7ID6Qbn5drvwWEj2vxz-cViALFQ0lhcHoW29UYsHXJWpGDyXLv5D6oiMwysDWC5sB1LzkdFz773ymQ3ZZ8FBQ4aSJgr2zufcudA_X7GzK5', '[{"name":"Traditional Khmer Herbal Massage (60 mins)","price":"$35.00","desc":"Ancient pressure-point therapy using warm herbal compresses to relieve tension and restore balance."},{"name":"Aromatherapy Deep Tissue (90 mins)","price":"$50.00","desc":"Custom blend of botanical essential oils tailored to alleviate fatigue and rejuvenate sore muscles."},{"name":"Personal Fitness Coaching Session","price":"$25.00","desc":"One-on-one session with certified trainer focusing on mobility, cardio, and strength."}]', 1, 2)
ON DUPLICATE KEY UPDATE `title`=VALUES(`title`);

-- Insert Special Offers
INSERT INTO `special_offers` (`id`, `title`, `promo_code`, `discount_percent`, `description`, `valid_from`, `valid_to`, `image_url`, `badge_text`, `is_active`, `display_order`) VALUES
(1, 'Direct Booking Privilege', 'INDRA15', 15, 'Book your stay directly on our official website and enjoy an exclusive 15% discount across all suites, complimentary daily breakfast, and flexible cancellation up to 24 hours prior to arrival.', '2026-01-01', '2026-12-31', 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1000&q=80', 'Best Rate Guarantee', 1, 1),
(2, 'Romantic Suite Getaway', 'LOVEINDRA', 20, 'Escape for a romantic getaway in our Indra Suite with Balcony. Includes a bottle of chilled sparkling wine on arrival, floral bed decoration, and late checkout until 3:00 PM.', '2026-02-01', '2026-12-31', 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&w=1000&q=80', 'Romantic Experience', 1, 2),
(3, 'Long Stay Sanctuary Package', 'STAYLONG', 25, 'Stay 5 nights or more and receive 25% off nightly rates, complimentary weekly laundry service, and 20% off all dining and spa treatments during your stay.', '2026-01-01', '2026-12-31', 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1000&q=80', 'Extended Stay', 1, 3)
ON DUPLICATE KEY UPDATE `title`=VALUES(`title`);

-- Insert Gallery Items
INSERT INTO `gallery` (`id`, `title`, `category`, `image_url`, `caption`, `display_order`) VALUES
(1, 'Stately Hotel Exterior', 'exterior', 'https://lh3.googleusercontent.com/aida/AP1WRLtHpM1LVwYuky4usi8aljQksBM3_T06H4btYM3gtlRqZ7b_NHp6dCow02XawKmSrDEyy4QtMR0PtPZlHSVqp-RD9bx6SzEFXe-vpfufKydm8eiddpQgw1Q1I9rh_Cc-FkEBv_gH40QUMF-3KrQRKburjx9jrdKTTwKVrOXZcMhiDl3gj8oQj_4ZGjvIzLvdtjrVXR_tWERJH_Z7FVUgaTDvTcckn8HPa1Xo0l-DpvWJs6OCpZDQhgPEsYcq', 'Architectural facade surrounded by tropical palms', 1),
(2, 'Deluxe King Interior', 'rooms', 'https://lh3.googleusercontent.com/aida/AP1WRLs-aT78HuC87zVBtlw78IAcVeqttvz1DzuDCFkgHQa0GjAqpJ7QEgkbAcIsJqkihNQyvb5xyVUyfpGCLZpUTsGnoI_Zd2-vfG3hGgzgX8ILxOjMzXh6zptxCM2mUT_5SpyirJMD2KE7cfOEm3QbJ69fnH6VMjX0sVrsXmM5Jm-XtIvZg9-B3Mseq2ffcjkq7LNDstvkdy5lRLn-NIFXZWhKbwJ1tFsvSH-_tFiOrkWNTCNfDxbD8XbxG-j2', 'Elegantly appointed Deluxe King bedroom', 2),
(3, 'The Bistro Restaurant', 'dining', 'https://lh3.googleusercontent.com/aida/AP1WRLu4xqDm5eXV-bc_ApYrUK1GnN0Euq-6ES4WN642l6K8VhewdBb_YkEtWSSt-tybo0AKJFBQh2oRWlfCx42rbsSmJsLPSmn2ODfXDog-y3cHuE5NTuWtSDiZptOZNk-bMlpk3s-xS7TRQHWRaUeUH0_bRiicGwQeGjy6gBDbaO4KosbM7QsKUNWT0PhQSHXUnhupahrd4i6fqtDtt53ZX2XGRn06_VQba3YHrkQ1BSNwkc5KeAJ3nMpX63ho', 'Sophisticated dining ambiance and evening lighting', 3),
(4, 'Fitness Center & Weights', 'wellness', 'https://lh3.googleusercontent.com/aida/AP1WRLuptPITXoiXpQR1wIOmYOuIMSUpJR1sTCXJga7uhGTXxKzccE6d21YAs-Fz3vugKf8Di3bkOx3Z2SAFqzNx65b_Uw7N7kpd85zK1LmfmQdCORWGDlOrtH72JS6rhGzsyzxnD8WonzUh6ObvlE7ID6Qbn5drvwWEj2vxz-cViALFQ0lhcHoW29UYsHXJWpGDyXLv5D6oiMwysDWC5sB1LzkdFz773ymQ3ZZ8FBQ4aSJgr2zufcudA_X7GzK5', 'Modern cardio and strength equipment', 4),
(5, 'Junior Suite Balcony Terrace', 'rooms', 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1200&q=80', 'Private balcony with scenic greenery view', 5),
(6, 'Indra Suite Lounge', 'rooms', 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80', 'Expansive suite living room with artisan furniture', 6)
ON DUPLICATE KEY UPDATE `title`=VALUES(`title`);

-- Insert Sample Bookings for Ledger Demo
INSERT INTO `bookings` (`id`, `booking_reference`, `room_id`, `guest_name`, `guest_email`, `guest_phone`, `check_in_date`, `check_out_date`, `adults`, `children`, `nights`, `room_rate`, `total_price`, `status`, `payment_status`, `special_requests`, `created_at`) VALUES
(1, 'IND-2026-8492', 1, 'Alexander Wright', 'alex.wright@example.com', '+1 (555) 234-8901', '2026-08-20', '2026-08-23', 2, 0, 3, 85.00, 255.00, 'confirmed', 'paid', 'High floor requested, quiet corner room if possible.', '2026-08-15 10:30:00'),
(2, 'IND-2026-9104', 3, 'Dr. Sophal Meas', 'sophal.meas@hospital.kh', '+855 12 334 556', '2026-08-18', '2026-08-22', 2, 1, 4, 180.00, 720.00, 'checked_in', 'paid', 'Airport transfer requested from Phnom Penh Int Airport at 14:00.', '2026-08-14 09:15:00'),
(3, 'IND-2026-7731', 2, 'Elena Rostova', 'elena.rostova@traveler.com', '+44 7700 900123', '2026-08-25', '2026-08-28', 1, 0, 3, 125.00, 375.00, 'pending', 'unpaid', 'Late check-in around 21:30 expected.', '2026-08-17 16:45:00'),
(4, 'IND-2026-6209', 1, 'Jonathan Chen', 'jchen@techasia.sg', '+65 9123 4567', '2026-08-10', '2026-08-14', 2, 0, 4, 85.00, 340.00, 'checked_out', 'paid', 'Vegetarian breakfast options.', '2026-08-05 11:20:00')
ON DUPLICATE KEY UPDATE `booking_reference`=VALUES(`booking_reference`);

-- Insert Sample Messages
INSERT INTO `messages` (`id`, `name`, `email`, `phone`, `subject`, `message`, `status`, `created_at`) VALUES
(1, 'Michael Brown', 'michael.b@consulting.co', '+855 98 765 432', 'Airport Pickup & Suite Inquiry', 'Hello Indra Hotel Team, I am visiting Phnom Penh next week for business and would like to confirm if your Indra Suite has a high-speed wired Ethernet connection and whether airport pickup can be arranged? Thank you!', 'unread', '2026-08-17 14:22:00'),
(2, 'Claire Dubois', 'claire.dubois@paris.fr', '+33 6 12 34 56 78', 'Romantic Anniversary Dinner Reservation', 'Good afternoon, we will be staying in your Junior Suite on August 26th for our 10th wedding anniversary. Could we arrange a special rooftop table and flowers at The Bistro? Best regards, Claire', 'read', '2026-08-16 11:05:00')
ON DUPLICATE KEY UPDATE `email`=VALUES(`email`);

-- Insert Site Settings
INSERT INTO `site_settings` (`setting_key`, `setting_value`) VALUES
('site_title', 'Indra Hotel | Contemporary Boutique Sanctuary in Phnom Penh'),
('site_meta_description', 'Experience refined luxury at Indra Hotel Phnom Penh. 12 contemporary designer suites with private balconies, saltwater pool, fitness center, and fine dining in Tuol Kork.'),
('site_meta_keywords', 'Indra hotel phnom penh, boutique hotel cambodia, luxury suites tuol kork, hotel with pool phnom penh, best hotel phnom penh'),
('google_analytics_id', 'G-INDRA2026'),
('hotel_notice_banner', '✨ Direct Booking Privilege: Complimentary Airport Pick-up on stays of 3+ nights.')
ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);
