apiVersion: v1
kind: ConfigMap
metadata:
  name: hotel-cms-config
  namespace: hotel-cms
data:
  APP_ENV: "production"
  DB_DRIVER: "mysql"
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  DB_NAME: "hotel_website"

---
apiVersion: v1
kind: Secret
metadata:
  name: hotel-cms-secret
  namespace: hotel-cms
type: Opaque
stringData:
  DB_USER: "hotel_user"
  DB_PASS: "hotel_k3s_secure_pass_2026"
  MYSQL_ROOT_PASSWORD: "mysql_root_k3s_secure_pass_2026"
